import test from 'node:test';
import assert from 'node:assert/strict';
import {fresh,hatch,normalize,advance,startRest,confirmRest,care,restReward} from '../engine.js';
import {setPromise,normalizeJourney,STORIES} from '../journey.js';
const T=1800000000000;
const born=()=>{const s=fresh(T);hatch(s,T,true);return s;};
function rest(s,minutes=30,now=T){setPromise(s,minutes,'read');assert.equal(startRest(s,now),true);assert.equal(confirmRest(s,now+minutes*60000),true);}
test('15,30,60 minute promises each award the exact confirmed length once',()=>{
 for(const m of [15,30,60]){const s=born();setPromise(s,m,'read');startRest(s,T);assert.equal(confirmRest(s,T+m*60000-1),false);assert.equal(s.journey.completed,0);assert.equal(confirmRest(s,T+m*60000),true);assert.equal(confirmRest(s,T+m*60000+1),false);assert.equal(s.restMinutes,m);assert.equal(s.journey.memories.length,1);assert.equal(s.journey.memories[0].intent,'read');}
});
test('changing the promise does not change an active session snapshot',()=>{const s=born();setPromise(s,15,'read');startRest(s,T);setPromise(s,60,'focus');assert.equal(s.rest.minutes,15);assert.equal(s.rest.intent,'read');confirmRest(s,T+900000);assert.equal(s.restMinutes,15);assert.equal(s.journey.memories[0].intent,'read');assert.equal(s.journey.promise.intent,'focus');});
test('no memory or rest credit for merely leaving or cancelling',()=>{const s=born();startRest(s,T);advance(s,480,{offline:true});assert.equal(s.restMinutes,0);assert.equal(s.journey.memories.length,0);s.rest=null;assert.equal(confirmRest(s,T+9999999),false);});
test('ordinary care changes needs but cannot unlock a life milestone',()=>{const s=born();care(s,'meal',T);care(s,'play-win',T);assert.equal(s.growth,0);assert.equal(s.journey.completed,0);assert.equal(s.journey.unlocked,0);});
test('confirmed rests unlock original room stories in order and save the journal',()=>{const s=born();for(let i=0;i<6;i++)rest(s,30,T+i*1900000);assert.equal(s.journey.unlocked,6);assert.deepEqual(s.journey.memories.map(x=>x.story),[0,1,2,3,4,5]);const v=normalize(JSON.parse(JSON.stringify(s)),T+20000000);assert.deepEqual(v.journey,s.journey);});
test('independent snack preparation restores hunger after the third rest',()=>{const s=born();rest(s);rest(s,30,T+1900000);s.hunger=10;rest(s,30,T+3800000);assert.equal(s.hunger,22);});
test('independent cleaning really clears a mess after fourth confirmed rest',()=>{const s=born();for(let i=0;i<3;i++)rest(s,30,T+i*1900000);s.poops=2;s.clean=52;rest(s,30,T+5700000);assert.equal(s.poops,1);assert.equal(s.clean,76);});
test('away time cannot make any care need worse, sick or dead',()=>{const s=born();const values=[s.hunger,s.happy,s.health,s.poops,s.clean,s.sick,s.dead];advance(s,100000,{offline:true});assert.deepEqual([s.hunger,s.happy,s.health,s.poops,s.clean,s.sick,s.dead],values);});
test('version3 migration keeps the pet without inventing a retrospective story',()=>{const v=normalize({version:3,hatched:true,growth:90,restMinutes:90,hunger:40,health:88,poops:1,clean:76,generation:3},T);assert.equal(v.form,3);assert.equal(v.generation,3);assert.equal(v.hunger,40);assert.equal(v.journey.completed,0);assert.equal(v.journey.memories.length,0);});
test('old in-progress thirty minute session keeps its exact deadline',()=>{const v=normalize({version:3,hatched:true,rest:{startedAt:T,readyAt:T+1800000}},T+1000);assert.equal(v.rest.minutes,30);assert.equal(v.rest.readyAt,T+1800000);assert.equal(confirmRest(v,T+1800000),true);});
test('invalid promises and forged display text are rejected by normalization',()=>{const j=normalizeJourney({promise:{minutes:999,intent:'<script>'},completed:2,memories:[{seq:1,story:999,minutes:30,intent:'read',at:T}]},T);assert.equal(j.promise.minutes,30);assert.equal(j.promise.intent,'rest');assert.equal(j.memories.length,0);const s=born();assert.equal(setPromise(s,2,'read'),false);assert.equal(startRest(s,T,90,'read'),false);});
test('journal retains at most thirty validated entries with duplicate protection',()=>{const s=born();for(let i=0;i<35;i++)rest(s,15,T+i*1000000);assert.equal(s.journey.completed,35);assert.equal(s.journey.memories.length,30);s.journey.memories.push(s.journey.memories.at(-1));const v=normalize(s,T+40000000);assert.equal(v.journey.memories.length,30);assert.ok(v.journey.memories.every(m=>STORIES[m.story]));});
test('unconfirmed timer survives reload but does not create a story',()=>{const s=born();setPromise(s,60,'meal');startRest(s,T);const v=normalize(s,T+5000000);assert.equal(v.rest.minutes,60);assert.equal(v.journey.memories.length,0);assert.equal(v.restMinutes,0);});
