import test from 'node:test';
import assert from 'node:assert/strict';
import {createDialogue,linesFor,BANK,mood} from '../dist/dialogue.js';
import {fresh,normalize} from '../dist/engine.js';
import {pet} from '../dist/character.js';
import {GOOD,BAD} from '../dist/world.js';
const healthy=()=>({...fresh(),hatched:true,form:1});
const storage=()=>{const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v)}};
test('all base dialogue is nonempty and authored',()=>{for(const a of Object.values(BANK))for(const t of a)assert.ok(typeof t==='string'&&t.length>0);assert.ok(Object.values(BANK).flat().length>140);});
test('healthy dialogue visits every candidate before repetition',()=>{const s=healthy(),d=createDialogue(storage(),'t',()=>.3),pool=linesFor(s);const got=Array.from({length:pool.length},()=>d.next(s));assert.equal(new Set(got).size,pool.length);assert.notEqual(got.at(-1),d.next(s));});
test('history survives reload',()=>{const st=storage(),s=healthy(),a=createDialogue(st,'x');const first=Array.from({length:12},()=>a.next(s));const b=createDialogue(st,'x');for(let i=0;i<12;i++)assert.ok(!first.includes(b.next(s)));});
test('normal and demo history are independent',()=>{const st=storage(),s=healthy();const a=createDialogue(st,'normal',()=>0),b=createDialogue(st,'demo',()=>0);assert.equal(a.next(s),b.next(s));});
test('storage failures do not stop speech',()=>{const d=createDialogue({getItem(){throw Error('blocked')},setItem(){throw Error('quota')}},'x');assert.ok(d.next(healthy()));});
test('corrupted saved dialogue is tolerated',()=>{const d=createDialogue({getItem:()=>'{oops',setItem(){}},'x');assert.ok(d.next(healthy()));});
test('unearned achievements and captures are absent',()=>{const s=healthy();assert.ok(!linesFor(s).some(t=>t.includes('ぼくの「できた」')));assert.ok(!linesFor(s).some(t=>t.includes('図鑑に残せて')));s.world.counts.read=1;s.world.captures=[{id:'002',count:1}];assert.ok(linesFor(s).some(t=>t.includes('ぼくの「できた」')));assert.ok(linesFor(s).some(t=>t.includes('泡沫猫')));});
for(const phase of BAD)test('distinct bad dialogue '+phase.level,()=>{const s=healthy();s.growth=phase.threshold;assert.equal(mood(s),'bad-'+phase.level);assert.deepEqual(linesFor(s),BANK['bad-'+phase.level]);const d=createDialogue(storage(),'x');const lines=Array.from({length:8},()=>d.next(s));assert.equal(new Set(lines).size,8);});
for(const [name,patch] of [['egg',{hatched:false}],['sleep',{sleeping:true}],['sick',{sick:true}],['hungry',{hunger:5}],['dead',{dead:true}]])test('state-specific '+name,()=>assert.equal(mood({...healthy(),...patch}),name));
test('idle timer does not burn dialogue while hidden or in a panel',()=>{const d=createDialogue(storage(),'x');d.idle(healthy(),false);assert.equal(d.info().recent.length,0);d.idle(healthy(),true);assert.equal(d.info().recent.length,1);d.idle(healthy(),true);assert.equal(d.info().recent.length,1);});
test('care response keeps original meaning',()=>{const d=createDialogue(storage(),'x'),s=healthy();assert.ok(BANK.full.includes(d.reaction('もう おなかいっぱい！',s)));assert.equal(d.reaction('先に「でんき」をつけてね。',s),'先に「でんき」をつけてね。');});
test('10 different bodies, not only 10 labels',()=>{const bodies=[];for(const [branch,phases] of [['good',GOOD],['bad',BAD]])for(const phase of phases){const s=healthy();s.growth=phase.threshold;const svg=pet(s);assert.ok(svg.includes(`data-look="${branch}-${phase.level}"`));bodies.push(svg.slice(svg.indexOf('>')+1));}assert.equal(new Set(bodies).size,10);});
test('saved state normalization is unchanged',()=>{const s=healthy();s.world.counts.read=3;assert.equal(normalize(s).world.counts.read,3);});
